#!/bin/bash
AVX=ON
AVX2=ON
SSE41=ON
SSE42=ON
CUDA=ON
OPENCL=ON
OPENCL_SVM=OFF
OPENGL=ON
VERSION=3.3.0
# GTK=OFF
GTK=ON
QT=OFF

PYTHON_BIN=/usr/bin/python3.6
# PYTHON_BIN=python
# PYTHON_BIN=/home/linker/.pyenv/shims/python
PYTHON_INCLUDE_DIR=$($PYTHON_BIN -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
PYTHON_PACKAGE_PATH=$($PYTHON_BIN -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

echo $PYTHON_BIN
$PYTHON_BIN --version
echo $PYTHON_INCLUDE_DIR
echo $PYTHON_PACKAGE_PATH

ROOT=$HOME

wget -c https://github.com/opencv/opencv/archive/$VERSION.tar.gz
tar xzf $VERSION.tar.gz -C $ROOT 

rm -rf $ROOT/opencv-$VERSION/cmake_binary
mkdir -p $ROOT/opencv-$VERSION/cmake_binary \
    && ls \
    && (cd $ROOT/opencv-$VERSION/cmake_binary \
    && cmake \
    -DBUILD_TIFF=ON \
    -DBUILD_opencv_java=OFF \
    -DCMAKE_BUILD_TYPE=RELEASE \
    -DWITH_CUDA=$CUDA \
    -DENABLE_AVX=$AVX \
    -DENABLE_AVX2=$AVX2 \
    -DENABLE_SSE41=$SSE41 \
    -DENABLE_SSE42=$SSE42 \
    -DENABLE_SSSE3=ON \
    -DWITH_GSTREAMER=ON \
    -DWITH_OPENGL=$OPENGL \
    -DWITH_LAPACK=ON \
    -DWITH_GTK=$GTK \
    -DWITH_QT=$QT \
    -DWITH_OPENCL=$OPENCL \
    -DWITH_OPENCL_SVM=$OPENCL_SVM \
    -DWITH_JPEG=ON \
    -DWITH_WEBP=ON \
    -DWITH_PNG=ON \
    -DWITH_IPP=ON \
    -DWITH_TBB=$TBB \
    -DWITH_EIGEN=ON \
    -DWITH_V4L=ON \
    -DWITH_FFMPEG=ON \
    -DENABLE_PRECOMPILED_HEADERS=ON \
    -DBUILD_PERF_TESTS=OFF \
    -DBUILD_TESTS=OFF \
    -DPYTHON3_EXECUTABLE=$PYTHON_BIN \
    -DPYTHON3_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython-3.6m.so \
    -DPYTHON3_INCLUDE_DIR=$PYTHON_INCLUDE_DIR \
    -DPYTHON3_PACKAGES_PATH=$PYTHON_PACKAGE_PATH \
    -DCMAKE_INSTALL_PREFIX="/usr/local" \
    -DINSTALL_C_EXAMPLES=OFF \
    ..  && make -j8 && sudo make install)

# -DCMAKE_INSTALL_PREFIX=$($PYTHON_BIN -c "import sys; print(sys.prefix)") \
# rm -rf $VERSION.tar.gz $ROOT/opencv-$VERSION
